<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /home/sean/buildkit/build/ext/sites/default/files/civicrm/ext/com.leftjoinlabs.peer/xml/schema/CRM/Peer/PeerPage.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:e7b2b452e658eadd24146fcae4f5da4f)
 */

/**
 * Database access object for the PeerPage entity.
 */
class CRM_Peer_DAO_PeerPage extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_peer_page';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique PeerPage ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * FK to PeerCampaign
   *
   * @var int unsigned
   */
  public $peer_campaign_id;

  /**
   * FK to Contact
   *
   * @var int unsigned
   */
  public $contact_id;

  /**
   * @var string
   */
  public $title;

  /**
   * Text written by the supporter to convince other people to click the button
   *
   * @var text
   */
  public $body;

  /**
   * The thermometer value the supporter hopes to achieve
   *
   * @var float
   */
  public $goal_amount;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_peer_page';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'peer_campaign_id', 'civicrm_peer_campaign', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('ID'),
          'description' => 'Unique PeerPage ID',
          'required' => TRUE,
          'table_name' => 'civicrm_peer_page',
          'entity' => 'PeerPage',
          'bao' => 'CRM_Peer_DAO_PeerPage',
          'localizable' => 0,
        ],
        'peer_campaign_id' => [
          'name' => 'peer_campaign_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Peer Campaign'),
          'description' => 'FK to PeerCampaign',
          'required' => TRUE,
          'table_name' => 'civicrm_peer_page',
          'entity' => 'PeerPage',
          'bao' => 'CRM_Peer_DAO_PeerPage',
          'localizable' => 0,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Contact ID'),
          'description' => 'FK to Contact',
          'required' => TRUE,
          'table_name' => 'civicrm_peer_page',
          'entity' => 'PeerPage',
          'bao' => 'CRM_Peer_DAO_PeerPage',
          'localizable' => 0,
          'html' => [
            'type' => 'EntityRef',
          ],
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Page Title'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'default' => 'NULL',
          'table_name' => 'civicrm_peer_page',
          'entity' => 'PeerPage',
          'bao' => 'CRM_Peer_DAO_PeerPage',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'body' => [
          'name' => 'body',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => ts('Body'),
          'description' => 'Text written by the supporter to convince other people to click the button',
          'default' => 'NULL',
          'table_name' => 'civicrm_peer_page',
          'entity' => 'PeerPage',
          'bao' => 'CRM_Peer_DAO_PeerPage',
          'localizable' => 0,
          'html' => [
            'type' => 'RichTextEditor',
          ],
        ],
        'goal_amount' => [
          'name' => 'goal_amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => ts('Goal Amount'),
          'description' => 'The thermometer value the supporter hopes to achieve',
          'precision' => [
            20,
            2
          ],
          'default' => 'NULL',
          'table_name' => 'civicrm_peer_page',
          'entity' => 'PeerPage',
          'bao' => 'CRM_Peer_DAO_PeerPage',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'peer_page', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'peer_page', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
